///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

  static const String fontsOpenSansBold = 'assets/fonts/OpenSans-Bold.ttf';
  static const String fontsOpenSansBoldItalic =
      'assets/fonts/OpenSans-BoldItalic.ttf';
  static const String fontsOpenSansExtraBold =
      'assets/fonts/OpenSans-ExtraBold.ttf';
  static const String fontsOpenSansExtraBoldItalic =
      'assets/fonts/OpenSans-ExtraBoldItalic.ttf';
  static const String fontsOpenSansItalic = 'assets/fonts/OpenSans-Italic.ttf';
  static const String fontsOpenSansLight = 'assets/fonts/OpenSans-Light.ttf';
  static const String fontsOpenSansLightItalic =
      'assets/fonts/OpenSans-LightItalic.ttf';
  static const String fontsOpenSansRegular =
      'assets/fonts/OpenSans-Regular.ttf';
  static const String fontsOpenSansSemiBold =
      'assets/fonts/OpenSans-SemiBold.ttf';
  static const String fontsOpenSansSemiBoldItalic =
      'assets/fonts/OpenSans-SemiBoldItalic.ttf';
  static const String iconsBubbles = 'assets/icons/bubbles.svg';
  static const String iconsFacebook = 'assets/icons/facebook.png';
  static const String iconsGoogle = 'assets/icons/google.png';
  static const String iconsGroups = 'assets/icons/groups.svg';
  static const String iconsPerson = 'assets/icons/person.svg';
  static const String iconsRepair = 'assets/icons/repair.svg';
  static const String iconsUpdate = 'assets/icons/update.svg';
  static const String imagesLogin = 'assets/images/login.png';
  static const String imagesLogo = 'assets/images/logo.png';
  static const String imagesWhatsappBack = 'assets/images/whatsapp_Back.png';
}
